---
apiVersion: v1
kind: Pod
metadata:
  name: devpod-template-hostnetwork
  namespace: devpod
  labels:
    devpod/template: "allenporter"
spec:
  hostNetwork: true
  # Workaround for https://github.com/loft-sh/devpod/issues/805
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command:
    - sh
    - -c
    - mkdir -p /tmp
